import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./vendors.min.css";
import "./icon.min.css";
import "./globals.css";
import "./responsive.css";
import "./green-energy.css";
// import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapProvider from './bootstrap-provider';
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer";


// Load Inter font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Traxsmart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={`${inter.variable} font-sans`}>
        <Navbar />
        <BootstrapProvider>
          {/* Push content down so it doesn’t overlap the sticky navbar */}
          <main data-mobile-nav-style="classic" className="pt-5">{children}</main>
        </BootstrapProvider>
        <Footer />
      </body>
    </html>
  );
}
