import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./vendors.min.css";
import "./icon.min.css";
import "./globals.css";
import "./responsive.css";
import "./green-energy.css";
// import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapProvider from './bootstrap-provider';
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer";
import navbarService from "@/services/Navbar.service";
import footerService from "@/services/Footer.service";
export const revalidate = 7776000;

// Load Inter font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Traxsmart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const services = await navbarService.getNavbar();
    const footerData = await footerService.getFooterData()

  return (
    <html lang="en">
      <body  className={`${inter.variable} font-sans`} data-mobile-nav-style="classic">
        <Navbar data = {services.data}/>
        <BootstrapProvider>
          {/* Push content down so it doesn’t overlap the sticky navbar */}
          <main>{children}</main>
        </BootstrapProvider>
        <Footer data={footerData.data} />
      </body>
    </html>
  );
}